name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # - name: test1
    #   id: test1
    #   uses: classroom-resources/autograding-python-grader@v1
    #   with:
    #     timeout: 10
    #     max-score: 1
    #     setup-command: pip install numpy pytest nbformat nbconvert
    - name: test_run_cmd_2
      id: test_run_cmd_2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: run_bundled_tests
        setup-command: pip install numpy pytest pytest-json-report nbformat nbconvert
        # command: pytest tests/test_hello.py tests/test_2.py -q
        command: pytest tests -q --json-report --json-report-file=pytest_report.json
        timeout: 10
        max-score: 20
    - name: Parse pytest results
      id: parse_results
      run: ./tests/parse_and_emit.sh
      shell: bash
      env:
        GITHUB_OUTPUT: ${{ github.output }}
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN_BUNDLED_TESTS_RESULTS: "${{steps.run_bundled_tests.outputs.result}}"
      with:
        runners: run_bundled_tests
