name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
          python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run test
      run: pytest -q
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
         runners: ubuntu-latest